dist: trusty

sudo: required

language: go

go:
  - 1.11

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

addons:
  apt:
    packages:
      - pkg-config
      - uuid-dev
      - libssl-dev
      - libseccomp-dev
      - squashfs-tools
      - libgpgme11-dev

matrix:
  include:
    - jdk: "openjdk8"
    - jdk: "oraclejdk8"
    - jdk: "oraclejdk9"

install:
  - test/install_trusty.sh

script:
  - test/run_simple.sh
