dist: trusty

sudo: required

language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

go:
  - 1.12

addons:
  apt:
    packages:

install:
  - test/install_trusty.sh

script:
  - test/run_simple.sh
